### PR TITLE
Shawnbranch

### PR DESCRIPTION
**Pull request by shawnbandy**
- Created a budget-route.js for PUT/POST/DELETE rqsts
- Created a household-route.js for PUT/POST/DELELTE rqsts
- Added an 'add' button to each major section on the dashboard that will redirect you to the /add page, but only display the type (income, expense, budget) that you selected
- Added an 'add your household' button to the nav. It looks kinda rn
- Added makeHousehold.js, which gives the ability to add a household (note that this is very basic and does not show the user which household they have selected)
- Added add.js which directs user to the proper /add page
- Added addData.js which handles user input for adding budget, income, and expense data
- Created a basic add.handlebars which is rendered when directed to /add page
- Added 3 basic partials, budget, expense, income, that render data on the dashboard page
- Other things are that my Prettier on VSCode doesn't like the " character so it replaced it with ' so idk

### CODE REVIEW

**Comment by shawnbandy** [comment]
I'm gonna take a break 2mrw lol and go outside

**Comment by parsonjd** [comment]
Wow.  I will approve this morning.

**Review by parsonjd — APPROVED** [review]
Nice work Shawn.  Be nice to see how it looks once approved.

**Review by Yuyitax — APPROVED** [review]
Looks great, thank you !

**Pull request merged**
